### PR TITLE
New Feature: Set visibility of icon

### PR DESCRIPTION
**Pull request by mschez**
This pull request allows set visibility of icon, also updates README.md and implement new visibility feature on demo project
### Customisation
`MaterialMenu.setVisibility(int visibility)`
or use attributes
`app:mm_visibility="integer`

Param: View.VISIBLE, View.INVISIBLE

### CODE REVIEW

**Comment by balysv** [comment]
Hey! Thanks for contributing :) looks like a useful feature.

There are a couple of issues that need discussing & fixing before I can merge it in:
1. I believe the API should be `MaterialMenu.setVisibility(boolean visible)` because there can only be two states (visible & gone) and `Drawable` class already has this API
2. An xml styleable attribute is added but it is not parsed and used. Have a look at https://github.com/balysv/material-menu/blob/master/library/src/main/java/com/balysv/materialmenu/MaterialMenuView.java#L66
3. The new attribute will not preserve its state after `Activity` recreation (configuration change or similar events). It should be saved and restored in https://github.com/balysv/material-menu/blob/master/library/src/main/java/com/balysv/materialmenu/MaterialMenuView.java#L219 and https://github.com/balysv/material-menu/blob/master/library/src/main/java/com/balysv/materialmenu/MaterialMenuBase.java#L168
4. Readme & demo updates with changes mentioned

**Comment by mschez** [comment]
Hi! Thanks for your guidelines, then I explain the latest changes.

1. Finally I renamed API to `MaterialMenu.setIconVisible(boolean visible)` and can be true or false, because I think that  `MaterialMenu.setVisibility(boolean visible)` is a wrong definition, should receive an visibility state and not an boolean param.
2. I added implementation for xml attributes, sorry, I forgot it in firsts commits.
3. Fixed preserve state, I save and restore its state in the proper place.
4. I updated README.md and demo.

Moreover I've also implemented new constructors with iconVisible.

**Comment by balysv** [comment]
My bad, I actually wanted to write `setVisible(boolean)` because it would be same as https://developer.android.com/reference/android/graphics/drawable/Drawable.html#setVisible(boolean, boolean), so go ahead and make the change and then I'll review :)

**Comment by balysv** [comment]
Thank you :bow:

**Pull request merged**
